---
driver:
  name: docker
  hostname: influxdb.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: influxdb
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - linux
        - influxdb
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_influxdata
          - influxdb
  pillars-from-files:
    linux_repo_influxdata.sls: tests/pillar/repo_influxdata.sls
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux.git

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: client
    provisioner:
      pillars-from-files:
        influxdb.sls: tests/pillar/client.sls

  - name: cluster
    provisioner:
      pillars-from-files:
        influxdb.sls: tests/pillar/cluster.sls

  - name: single
    provisioner:
      pillars-from-files:
        influxdb.sls: tests/pillar/single.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
